### ISSUE TITLE
Wrong classname for cache implementation

### ISSUE THREAD

**Issue by reyostallenberg** [psr-discovery/discovery#5]
The discover class test if `PsrDiscovery\Implementations\Psr6\Cache` exists.  
See: https://github.com/psr-discovery/discovery/blob/9fb31dca2030accd9d3de21fb8806478e9df5b2b/src/Discover.php#L90

Which will always be false, because the class name is `PsrDiscovery\Implementations\Psr6\Caches` with a trailing s  
See: https://github.com/psr-discovery/cache-implementations/blob/1.x/src/Implementations/Psr6/Caches.php

As the class is final there is also no way to fix this temporary for me.

What should be the correct way to fix this? I can create a PR for it.

**Comment by evansims** [comment]
Good catch, thanks for letting me know! If you'd like to create a PR fixing it that would be excellent 👍

**Comment by evansims** [comment]
Fixed in [1.1.2](https://github.com/psr-discovery/discovery/releases/tag/1.1.2) — thanks for your contribution!
